theme:
  #  active: "20, 20, 20" # current playing song in list
  #  banner: "41, 113, 26" # the "spotify-tui" banner on launch
  #  error_border: "237, 0, 0" # error dialog border
  #  error_text: "25, 0, 0" # error message text (e.g. "Spotify API reported error 404")
  #  hint: "0, 126, 93" # hint text in errors
  #  hovered: "0, 0, 0" # hovered pane border
  #  inactive: "165, 165, 165" # borders of inactive panes
  #  playbar_background: "20, 20, 20" # background of progress bar
  #  playbar_progress: "38, 75, 40" # filled-in part of the progress bar
  #  playbar_progress_text: "160, 210, 162" # song length and time played/left indicator in the progress bar
  #  playbar_text: "20, 20, 20" # artist name in player pane
  #  selected: "0, 0, 0" # a) selected pane border, b) hovered item in list, & c) track title in player
  #  text: "20, 20, 20" # text in panes
  #  header: "15, 60, 20" # header text in panes (e.g. 'Title', 'Artist', etc.)

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 12
  # Enable text emphasis (typically italic/bold text styling). Disabling this might be important if the terminal config is otherwise restricted and rendering text escapes interferes with the UI.
  enable_text_emphasis: true
  # Controls whether to show a loading indicator in the top right of the UI whenever communicating with Spotify API
  show_loading_indicator: true
  # Disables the responsive layout that makes the search bar smaller on bigger
  # screens and enforces a wide search bar
  enforce_wide_search_bar: true
  # Determines the text icon to display next to "liked" Spotify items, such as
  # liked songs and albums, or followed artists. Can be any length string.
  # These icons require a patched nerd font.
  liked_icon: ♥
  shuffle_icon: 🔀
  repeat_track_icon: 🔂
  repeat_context_icon: 🔁
  playing_icon: ▶
  paused_icon: ⏸

keybindings:
  # Key stroke can be used if it only uses two keys:
  # ctrl-q works,
  # ctrl-alt-q doesn't.
  back: "ctrl-q"

  jump_to_album: "a"

  # Shift modifiers use a capital letter (also applies with other modifier keys
  # like ctrl-A)
  jump_to_artist_album: "A"

  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "+"
  toggle_playback: " "
  seek_backwards: "<"
  seek_forwards: ">"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  shuffle: "ctrl-s"
  repeat: "r"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "z"
